INSERT INTO estado VALUES ('Acre', 'AC');
INSERT INTO estado VALUES ('Alagoas', 'AL');
INSERT INTO estado VALUES ('Amapá', 'AP');
INSERT INTO estado VALUES ('Amazonas', 'AM');
INSERT INTO estado VALUES ('Bahia', 'BA');
INSERT INTO estado VALUES ('Ceará', 'CE');
INSERT INTO estado VALUES ('Distrito Federal', 'DF');
INSERT INTO estado VALUES ('Espírito Santo','ES');
INSERT INTO estado VALUES ('Goiás', 'GO');
INSERT INTO estado VALUES ('Maranhão', 'MA');
INSERT INTO estado VALUES ('Mato Grosso', 'MT');
INSERT INTO estado VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO estado VALUES ('Minas Gerais', 'MG');
INSERT INTO estado VALUES ('Pará', 'PA');
INSERT INTO estado VALUES ('Paraíba', 'PB');
INSERT INTO estado VALUES ('Paraná', 'PR');
INSERT INTO estado VALUES ('Pernambuco', 'PE');
INSERT INTO estado VALUES ('Piauí', 'PI');
INSERT INTO estado VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO estado VALUES ('Rio Grande do Norte', 'RN',);
INSERT INTO estado VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO estado VALUES ('Rondônia', 'RO');
INSERT INTO estado VALUES ('Roraima', 'RR');
INSERT INTO estado VALUES ('Santa Catarina', 'SC');
INSERT INTO estado VALUES ('São Paulo', 'SP');
INSERT INTO estado VALUES ('Sergipe', 'SE');
INSERT INTO estado VALUES ('Tocantins', 'TO'); 